class Artist_Names:
    names = [
        "Taylor Swift",
        'Drake',
        'Bad Bunny',
        'The Weeknd',
        'Ed Sheeran',
        'Ariana Grande',
        'Eminem',
        'Justin Bieber',
        'Post Malone',
        'Kanye West',
        'BTS',
        'Billie Eilish',
        'J Balvin',
        'Rihanna',
        'Coldplay',
        'Travis Scott',
        'Dua Lipa',
        'Juice WRLD',
        'Imagine Dragons',
        'XXXTENTACION',
        'Ozuna',
        'David Guetta',
        'Kendrick Lamar',
        'Bruno Mars',
        'Maroon 5',
        'Khalid',
        'Lana Del Rey',
        'Calvin Harris',
        'Shawn Mendes',
        'Beyonce',
        'KAROL G',
        'Sam Smith',
        'Daddy Yankee',
        'Queen',
        'Harry Styles',
        'Future',
        'Lady Gaga',
        'One Direction',
        'Rauw Alejandro',
        'J. Cole',
        'Nicki Minaj',
        'Adele',
        'Anuel AA',
        'Shakira',
        'Chris Brown',
        'SZA',
        'The Beatles',
        'Linkin Park',
        'Arctic Monkeys',
        'Doja Cat'
    ]

